# Generated by Django 3.1.4 on 2020-12-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_matchingentry_triplet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingentry',
            old_name='samey',
            new_name='person_above_adventure',
        ),
    ]
