# Generated by Django 3.1.4 on 2020-12-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20201221_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingentry',
            old_name='exchange_preference',
            new_name='talkativity_preference',
        ),
    ]
