# Generated by Django 3.1.4 on 2021-01-17 18:08

from django.db import migrations, models
import matching.validators


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_auto_20201225_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingentry',
            name='album_macrogenre',
            field=models.CharField(choices=[('Country, Folk & Blues', 'Country, Folk & Blues'), ('Classical', 'Classical'), ('Electronic and Dance', 'Electronic and Dance'), ('Hip Hop and R&B', 'Hip Hop and R&B'), ('Indie, Indie Pop, Emo and Pop Punk', 'Indie, Indie Pop, Emo and Pop Punk'), ('Jazz, Soul, Neo-Soul and Funk', 'Jazz, Soul, Neo-Soul and Funk'), ('Pop', 'Pop'), ('Rock, Metal, Punk, Noise, Prog, Post-Rock, Industrial', 'Rock, Metal, Punk, Noise, Prog, Post-Rock, Industrial'), ('Other', 'Other')], help_text="What macro genre would you classify the album you're recommending in?", max_length=60),
        ),
        migrations.AlterField(
            model_name='matchingentry',
            name='match_macrogenre',
            field=models.JSONField(help_text='Which macrogenres would you be happy to receive recommendations from, in order of preference? Select at least 2. Valid choices are <select><option>Country, Folk & Blues (Country, Folk & Blues)</option><option>Classical (Classical)</option><option>Electronic and Dance (Electronic and Dance)</option><option>Hip Hop and R&B (Hip Hop and R&B)</option><option>Indie, Indie Pop, Emo and Pop Punk (Indie, Indie Pop, Emo and Pop Punk)</option><option>Jazz, Soul, Neo-Soul and Funk (Jazz, Soul, Neo-Soul and Funk)</option><option>Pop (Pop)</option><option>Rock, Metal, Punk, Noise, Prog, Post-Rock, Industrial (Rock, Metal, Punk, Noise, Prog, Post-Rock, Industrial)</option><option>Other (Other)</option></select>', validators=[matching.validators.ListOfStringsValidator('Your match macrogenre was invalid, you might not have selected enough genres.', 'match macrogenre', choices=[('Country, Folk & Blues', 'Country, Folk & Blues'), ('Classical', 'Classical'), ('Electronic and Dance', 'Electronic and Dance'), ('Hip Hop and R&B', 'Hip Hop and R&B'), ('Indie, Indie Pop, Emo and Pop Punk', 'Indie, Indie Pop, Emo and Pop Punk'), ('Jazz, Soul, Neo-Soul and Funk', 'Jazz, Soul, Neo-Soul and Funk'), ('Pop', 'Pop'), ('Rock, Metal, Punk, Noise, Prog, Post-Rock, Industrial', 'Rock, Metal, Punk, Noise, Prog, Post-Rock, Industrial'), ('Other', 'Other')], min_items=2)]),
        ),
    ]
