# Generated by Django 3.1.4 on 2021-01-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_auto_20210117_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingentry',
            name='album_microgenre',
            field=models.CharField(blank=True, help_text='What microgenre(s) would you associate with your album?', max_length=200),
        ),
    ]
